#!/bin/bash

ARGS="--param ../Labs/2223-pf/C1-config.xml"
ARGS+=" --lab ../Labs/2223-pf/C2-lab.xml"
ARGS+=" --grid ../Labs/2223-pf/C2-grid.xml"
#ARGS+=" --scoring 1"
ARGS+=" --gps"
ARGS+=" --compass"
(cd simulator; ./simulator $ARGS) &

sleep 2

(cd Viewer; ./Viewer --autoconnect) &

sleep 2

(cd pf2Client_v1; ./s1.sh )


killall simulator
killall Viewer
echo Bye
